"""Update generated website/CV data and optionally publish the compiled CV PDF."""

from __future__ import annotations

import argparse
import datetime as dt
import html
import json
import re
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PUBLICATIONS_JS = ROOT / "assets" / "publications.js"
TALKS_JSON = ROOT / "scripts" / "talks.json"
TALKS_JS = ROOT / "assets" / "talks.js"
CV_EXTRA = ROOT / "scripts" / "cv-extra-publications.json"
CV_TEX = ROOT / "cv" / "Michiel_De_Wilde_CV.tex"
CV_PDF = ROOT / "cv" / "Michiel_De_Wilde_CV.pdf"
ASSET_PDF = ROOT / "assets" / "CV_Michiel_De_Wilde.pdf"
BEGIN_PUBLICATIONS = "% BEGIN GENERATED PUBLICATIONS"
END_PUBLICATIONS = "% END GENERATED PUBLICATIONS"
BEGIN_TALKS = "% BEGIN GENERATED TALKS"
END_TALKS = "% END GENERATED TALKS"

PUBLICATIONS_HTML = {"en": ROOT / "publications.html", "nl": ROOT / "nl" / "publications.html"}
CV_HTML = {"en": ROOT / "cv.html", "nl": ROOT / "nl" / "cv.html"}
BEGIN_PUB_HTML = "<!-- BEGIN GENERATED PUBLICATIONS -->"
END_PUB_HTML = "<!-- END GENERATED PUBLICATIONS -->"
BEGIN_TALKS_HTML = "<!-- BEGIN GENERATED TALKS -->"
END_TALKS_HTML = "<!-- END GENERATED TALKS -->"
BEGIN_PUB_JSONLD = "<!-- BEGIN GENERATED PUBLICATIONS JSON-LD -->"
END_PUB_JSONLD = "<!-- END GENERATED PUBLICATIONS JSON-LD -->"
HTML_GENERATED_NOTE = "<!-- Generated by scripts/build_cv.py. Do not edit by hand. -->"

TYPE_LABELS = {
    "en": {"paper": "Paper", "preprint": "Preprint"},
    "nl": {"paper": "Artikel", "preprint": "Preprint"},
}
MONTH_ABBREVIATIONS = {
    "en": ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    "nl": ["jan", "feb", "mrt", "apr", "mei", "jun", "jul", "aug", "sep", "okt", "nov", "dec"],
}
EMPTY_PUBLICATIONS_HTML = {
    "en": (
        '<div class="empty-orbit"><i></i><i></i><i></i></div>\n'
        '<p class="kicker">Watch this space</p>\n'
        "<h2>The first entries are<br>still taking shape.</h2>\n"
        "<p>New papers and preprints will appear here. In the meantime, you can explore the ideas that guide my work.</p>\n"
        '<a class="button primary" href="index.html#research">Research interests <span>↗</span></a>'
    ),
    "nl": (
        '<div class="empty-orbit"><i></i><i></i><i></i></div>\n'
        '<p class="kicker">Hou deze plek in de gaten</p>\n'
        "<h2>De eerste items<br>krijgen nog vorm.</h2>\n"
        "<p>Nieuwe artikels en preprints verschijnen hier binnenkort. Ondertussen kan je de ideeën verkennen die mijn werk sturen.</p>\n"
        '<a class="button primary" href="index.html#research">Onderzoeksinteresses <span>↗</span></a>'
    ),
}

LATEX_REPLACEMENTS = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def latex_escape(value: str) -> str:
    return "".join(LATEX_REPLACEMENTS.get(char, char) for char in str(value or ""))


def load_publications() -> list[dict]:
    text = PUBLICATIONS_JS.read_text(encoding="utf-8")
    match = re.search(r"window\.PUBLICATIONS\s*=\s*(\[.*\]);", text, re.S)
    if not match:
        raise ValueError(f"Could not find window.PUBLICATIONS in {PUBLICATIONS_JS}")
    publications = json.loads(match.group(1))
    if CV_EXTRA.exists():
        publications.extend(json.loads(CV_EXTRA.read_text(encoding="utf-8-sig")))
    return sorted(
        publications,
        key=lambda item: (str(item.get("year", "")), str(item.get("title", ""))),
        reverse=True,
    )


def load_talks() -> list[dict]:
    talks = json.loads(TALKS_JSON.read_text(encoding="utf-8-sig")) if TALKS_JSON.exists() else []
    return sorted(talks, key=lambda item: str(item.get("date", "")), reverse=True)


def load_website_publications() -> list[dict]:
    text = PUBLICATIONS_JS.read_text(encoding="utf-8")
    match = re.search(r"window\.PUBLICATIONS\s*=\s*(\[.*\]);", text, re.S)
    if not match:
        raise ValueError(f"Could not find window.PUBLICATIONS in {PUBLICATIONS_JS}")
    return json.loads(match.group(1))


def format_date_display(value: str, lang: str) -> str:
    try:
        date = dt.date.fromisoformat(str(value))
    except ValueError:
        return html.escape(str(value or ""), quote=False)
    month = MONTH_ABBREVIATIONS[lang][date.month - 1]
    return f"{date.day:02d} {month} {date.year}"


def render_pub_item_html(publication: dict, lang: str) -> str:
    year = html.escape(str(publication.get("year", "")), quote=False)
    kind = str(publication.get("type", "")).strip().casefold()
    type_label = TYPE_LABELS[lang].get(kind, html.escape(str(publication.get("type", "")), quote=False))
    title = html.escape(str(publication.get("title", "")), quote=False)
    authors = html.escape(str(publication.get("authors", "")), quote=False)
    venue = html.escape(str(publication.get("venue", "")), quote=False)
    url = html.escape(str(publication.get("url", "")).strip(), quote=True)
    return (
        f'<article class="pub-item"><span>{year}</span><div><p>{type_label}</p>'
        f"<h3>{title}</h3><small>{authors} · {venue}</small></div>"
        f'<a href="{url}" target="_blank" rel="noopener">↗</a></article>'
    )


def render_talk_item_html(talk: dict, lang: str) -> str:
    date_attr = html.escape(str(talk.get("date", "")), quote=True)
    date_display = format_date_display(talk.get("date", ""), lang)
    event = html.escape(str(talk.get("event", "")).strip(), quote=False)
    venue = html.escape(str(talk.get("venue", "")).strip(), quote=False)
    location = f"{event} &middot; {venue}" if event and venue else (event or venue)
    title = html.escape(str(talk.get("title", "")), quote=False)
    return (
        f'<article class="talk-item"><time datetime="{date_attr}">{date_display}</time>'
        f'<div><p class="institution">{location}</p><h3>{title}</h3></div></article>'
    )


def publications_json_ld(publications: list[dict]) -> str:
    items = []
    for index, publication in enumerate(publications, start=1):
        authors = [name.strip() for name in str(publication.get("authors", "")).split(",") if name.strip()]
        kind = str(publication.get("type", "")).strip().casefold()
        article: dict = {
            "@type": "ScholarlyArticle",
            "headline": publication.get("title", ""),
            "name": publication.get("title", ""),
            "author": [{"@type": "Person", "name": name} for name in authors],
            "datePublished": str(publication.get("year", "")),
            "url": publication.get("url", ""),
        }
        if publication.get("venue"):
            article["isPartOf"] = {"@type": "Periodical", "name": publication["venue"]}
        if kind == "preprint":
            article["creativeWorkStatus"] = "Preprint"
        items.append({"@type": "ListItem", "position": index, "item": article})
    payload = {"@context": "https://schema.org", "@type": "ItemList", "itemListElement": items}
    return json.dumps(payload, ensure_ascii=False, indent=2)


def update_publications_html() -> None:
    publications = load_website_publications()
    for lang, path in PUBLICATIONS_HTML.items():
        if publications:
            items = "\n".join(render_pub_item_html(publication, lang) for publication in publications)
            generated = f'<div class="publication-list">\n{items}\n</div>'
        else:
            generated = EMPTY_PUBLICATIONS_HTML[lang]
        text = path.read_text(encoding="utf-8")
        text, pub_count = replace_generated_block(text, BEGIN_PUB_HTML, END_PUB_HTML, generated, HTML_GENERATED_NOTE)
        if pub_count != 1:
            raise ValueError(f"Expected exactly one generated publications block in {path}; found {pub_count}")
        json_ld = f'<script type="application/ld+json">\n{publications_json_ld(publications)}\n</script>' if publications else ""
        text, jsonld_count = replace_generated_block(text, BEGIN_PUB_JSONLD, END_PUB_JSONLD, json_ld, "")
        if jsonld_count != 1:
            raise ValueError(f"Expected exactly one generated publications JSON-LD block in {path}; found {jsonld_count}")
        path.write_text(text, encoding="utf-8")
        print(f"Updated {path.relative_to(ROOT)} with {len(publications)} publication(s).")


def update_talks_html() -> None:
    talks = load_talks()
    for lang, path in CV_HTML.items():
        generated = "\n".join(render_talk_item_html(talk, lang) for talk in talks)
        text = path.read_text(encoding="utf-8")
        text, talk_count = replace_generated_block(text, BEGIN_TALKS_HTML, END_TALKS_HTML, generated, HTML_GENERATED_NOTE)
        if talk_count != 1:
            raise ValueError(f"Expected exactly one generated talks block in {path}; found {talk_count}")
        path.write_text(text, encoding="utf-8")
        print(f"Updated {path.relative_to(ROOT)} with {len(talks)} talk(s).")


def write_talks_js() -> None:
    talks = load_talks()
    payload = json.dumps(talks, ensure_ascii=False, indent=2)
    TALKS_JS.write_text(
        "// Generated by scripts/build_cv.py - do not edit manually.\n"
        f"window.TALKS = {payload};\n",
        encoding="utf-8",
    )
    print(f"Updated {TALKS_JS.relative_to(ROOT)} with {len(talks)} talk(s).")


def format_talk_date(value: str, style: str) -> str:
    try:
        date = dt.date.fromisoformat(str(value))
    except ValueError:
        return str(value or "")
    if style == "latex":
        return date.strftime("%d/%m/%Y")
    return date.strftime("%d %b %Y")


def talk_location(talk: dict, separator: str = " - ") -> str:
    event = str(talk.get("event", "")).strip()
    venue = str(talk.get("venue", "")).strip()
    if event and venue:
        return f"{event}{separator}{venue}"
    return event or venue


def render_talk(talk: dict) -> str:
    date = latex_escape(format_talk_date(talk.get("date", ""), "latex"))
    location = latex_escape(talk_location(talk, separator=" ("))
    if " (" in location and not location.endswith(")"):
        location += ")"
    title = latex_escape(talk.get("title", ""))
    return (
        f"{date} &\\textbf{{{location}}}\\newline\n"
        f"Title: {title}\\\\"
    )


def publication_label(publication: dict) -> str:
    kind = str(publication.get("type", "")).strip().casefold()
    if kind in {"under review", "submitted"}:
        return "[under review] "
    if kind == "preprint":
        return "[preprint] "
    return ""


def render_publication(publication: dict) -> str:
    year = latex_escape(publication.get("year", ""))
    label = latex_escape(publication_label(publication))
    title = latex_escape(publication.get("title", ""))
    authors = latex_escape(publication.get("authors", ""))
    venue = latex_escape(publication.get("venue", ""))
    url = str(publication.get("url", "")).strip()
    venue_line = f"\\href{{{url}}}{{\\textit{{{venue}}}}}" if url else f"\\textit{{{venue}}}"
    return (
        f"{year} &\n"
        f"{label}\\textbf{{{title}}} \\newline\n"
        f"{authors}. \\newline\n"
        f"{venue_line}. \\\\"
    )


def replace_generated_block(text: str, begin: str, end: str, generated: str, note: str) -> tuple[str, int]:
    pattern = re.compile(f"{re.escape(begin)}.*?{re.escape(end)}", re.S)
    replacement = f"{begin}\n{note}\n{generated}\n{end}"
    return pattern.subn(lambda _: replacement, text)


def update_tex() -> None:
    publications = load_publications()
    talks = load_talks()
    publication_block = "\n".join(render_publication(publication) for publication in publications)
    talks_block = "\n\n".join(render_talk(talk) for talk in talks)
    text = CV_TEX.read_text(encoding="utf-8")
    text, publication_count = replace_generated_block(
        text,
        BEGIN_PUBLICATIONS,
        END_PUBLICATIONS,
        publication_block,
        "% This block is generated by scripts/build_cv.py. Edit assets/publications.js or\n"
        "% scripts/cv-extra-publications.json, then run python scripts/build_cv.py.",
    )
    text, talks_count = replace_generated_block(
        text,
        BEGIN_TALKS,
        END_TALKS,
        talks_block,
        "% This block is generated by scripts/build_cv.py. Edit scripts/talks.json,\n"
        "% then run python scripts/build_cv.py.",
    )
    if publication_count != 1:
        raise ValueError(f"Expected exactly one generated publications block in {CV_TEX}; found {publication_count}")
    if talks_count != 1:
        raise ValueError(f"Expected exactly one generated talks block in {CV_TEX}; found {talks_count}")
    CV_TEX.write_text(text, encoding="utf-8")
    print(f"Updated {CV_TEX.relative_to(ROOT)} with {len(publications)} publication(s) and {len(talks)} talk(s).")


def run(command: list[str], cwd: Path) -> bool:
    print("Running:", " ".join(command))
    try:
        subprocess.run(command, cwd=cwd, check=True)
        return True
    except (FileNotFoundError, subprocess.CalledProcessError):
        return False


def compile_pdf() -> None:
    workdir = CV_TEX.parent
    commands = [
        ["latexmk", "-pdf", "-interaction=nonstopmode", "-halt-on-error", CV_TEX.name],
        ["pdflatex", "-interaction=nonstopmode", "-halt-on-error", CV_TEX.name],
    ]
    for command in commands:
        if run(command, workdir):
            if command[0] == "pdflatex":
                run(command, workdir)
            break
    else:
        raise RuntimeError("No LaTeX compiler succeeded. Install latexmk/pdflatex or use the GitHub Action.")
    if not CV_PDF.exists():
        raise FileNotFoundError(f"Expected compiled PDF at {CV_PDF}")
    shutil.copy2(CV_PDF, ASSET_PDF)
    print(f"Copied {CV_PDF.relative_to(ROOT)} to {ASSET_PDF.relative_to(ROOT)}.")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--no-compile", action="store_true", help="Only rewrite generated data and LaTeX blocks.")
    args = parser.parse_args()
    write_talks_js()
    update_tex()
    update_publications_html()
    update_talks_html()
    if not args.no_compile:
        compile_pdf()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
