"""Generate website publication data from public ORCID and arXiv records."""

import json
import re
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

ORCID_ID = "0009-0001-8236-884X"
AUTHOR_NAME = "Michiel De Wilde"
ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "assets" / "publications.js"
MANUAL = ROOT / "scripts" / "manual-publications.json"
USER_AGENT = "MichielDeWildeWebsite/1.0 (michiel.dewilde@ist.ac.at)"


def fetch(url, accept):
    request = urllib.request.Request(
        url, headers={"Accept": accept, "User-Agent": USER_AGENT}
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read()


def clean(value):
    return re.sub(r"\s+", " ", value or "").strip()


def get_ids(work):
    result = {}
    for item in (work.get("external-ids") or {}).get("external-id") or []:
        kind = clean(item.get("external-id-type")).lower()
        value = clean(item.get("external-id-value"))
        if kind and value:
            result[kind] = value
    return result


def from_orcid():
    url = f"https://pub.orcid.org/v3.0/{ORCID_ID}/works"
    data = json.loads(fetch(url, "application/json"))
    publications = []
    for group in data.get("group") or []:
        summaries = group.get("work-summary") or []
        if not summaries:
            continue
        work = summaries[0]
        title = clean(((work.get("title") or {}).get("title") or {}).get("value"))
        if not title:
            continue
        ids = get_ids(work)
        date = work.get("publication-date") or {}
        year = clean((date.get("year") or {}).get("value")) or "Forthcoming"
        url_value = clean((work.get("url") or {}).get("value"))
        if not url_value and ids.get("doi"):
            url_value = f"https://doi.org/{ids['doi']}"
        if not url_value and ids.get("arxiv"):
            url_value = f"https://arxiv.org/abs/{ids['arxiv']}"
        publications.append({
            "type": "preprint" if "preprint" in clean(work.get("type")).lower() else "paper",
            "year": year,
            "title": title,
            "authors": AUTHOR_NAME,
            "venue": clean((work.get("journal-title") or {}).get("value"))
            or ("arXiv" if ids.get("arxiv") else "ORCID"),
            "url": url_value or f"https://orcid.org/{ORCID_ID}",
            "_ids": ids,
        })
    return publications


def from_arxiv():
    params = urllib.parse.urlencode({
        "search_query": 'au:"De Wilde, M"',
        "start": 0,
        "max_results": 100,
        "sortBy": "submittedDate",
        "sortOrder": "descending",
    })
    root = ET.fromstring(fetch(
        f"https://export.arxiv.org/api/query?{params}", "application/atom+xml"
    ))
    atom = {"a": "http://www.w3.org/2005/Atom"}
    publications = []
    for entry in root.findall("a:entry", atom):
        authors = [
            clean(author.findtext("a:name", default="", namespaces=atom))
            for author in entry.findall("a:author", atom)
        ]
        # The author search is broad; only accept Michiel's exact full name.
        if AUTHOR_NAME.casefold() not in {author.casefold() for author in authors}:
            continue
        entry_url = clean(entry.findtext("a:id", default="", namespaces=atom))
        arxiv_id = re.sub(r"v\d+$", "", entry_url.rsplit("/", 1)[-1])
        published = clean(entry.findtext("a:published", default="", namespaces=atom))
        publications.append({
            "type": "preprint",
            "year": published[:4] or "Forthcoming",
            "title": clean(entry.findtext("a:title", default="", namespaces=atom)),
            "authors": ", ".join(authors),
            "venue": "arXiv",
            "url": entry_url,
            "_ids": {"arxiv": arxiv_id},
        })
    return publications


def publication_key(publication):
    ids = publication.get("_ids", {})
    if ids.get("doi"):
        return "doi:" + ids["doi"].lower()
    if ids.get("arxiv"):
        return "arxiv:" + ids["arxiv"].lower()
    return "title:" + re.sub(r"\W", "", publication["title"]).casefold()


def main():
    manual = json.loads(MANUAL.read_text(encoding="utf-8"))
    merged = {}
    # arXiv comes last because it includes complete author lists.
    for publication in [*manual, *from_orcid(), *from_arxiv()]:
        merged[publication_key(publication)] = publication
    publications = sorted(
        merged.values(),
        key=lambda item: (item.get("year", ""), item.get("title", "")),
        reverse=True,
    )
    for publication in publications:
        publication.pop("_ids", None)
    payload = json.dumps(publications, ensure_ascii=False, indent=2)
    OUTPUT.write_text(
        "// Generated by scripts/sync_publications.py — do not edit manually.\n"
        f"window.PUBLICATIONS = {payload};\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(publications)} publication(s)")


if __name__ == "__main__":
    main()
